name: Build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Alpine
        uses: jirutka/setup-alpine@v1
        with:
          packages: >
            build-base
            luajit-dev
      - name: Build library
        run: make
        shell: alpine.sh {0}
